Header header

float32 LL_level 
# Lower left WiFi signal in a normalized scale (1-100)

float32 LR_level 
# Lower Right WiFi signal in a normalized scale (1-100)

float32 UL_level 
# Upper Left WiFi signal in a normalized scale (1-100)

float32 UR_level 
# Upper Right WiFi signal in a normalized scale (1-100)

float32 C_level 
# Center WiFi signal in a normalized scale (1-100)

float32 LL_level_abs 
# Lower Left WiFi signal in dBm

float32 LR_level_abs 
# Lower Right WiFi signal in dBm

float32 UL_level_abs 
# Lower Left WiFi signal in dBm

float32 UR_level_abs 
# Upper Right WiFi signal in dBm

float32 C_level_abs 
# Center WiFi signal in dBm


