#!/usr/bin/env bash

echo "usage: ./${0##*/} <num-robots>"

export DEST_FOLDER="/tmp"
export NUM_ROBOTS=5

# ========================================================================================

function print_blue(){
	printf "\033[34;1m"
	printf "$@ \n"
	printf "\033[0m"
}


function print_red(){
	printf "\033[31;1m"
	printf "$@ \n"
	printf "\033[0m"
}

function check_status(){
	if [ $? -eq 0 ]
	then
	  print_blue "Successfully performed operation"
	else
	  print_red "Could not perform operation" >&2
	fi
}

# ========================================================================================

if [[ -n "$MR3D_HOME" ]]; then
	source $MR3D_HOME/source_all.bash
else
	print_red "please source the patrolling workspace before performing any operation!"
	exit 1
fi

# ========================================================================================

echo "saving map"

echo "trying to save shared map"
rosservice call /volumetric_mapping/save_map "file_path: '$DEST_FOLDER/map.bt'"
check_status

# save the map in the volumetric mapping system of each robot (for independent volumetric mapping systems)
for i in `seq 1 $NUM_ROBOTS`;
do
	echo "trying to save ugv$i map"
	rosservice call /volumetric_mapping_ugv$i/save_map "file_path: '$DEST_FOLDER/map_ugv$i.bt'"
	check_status
done

echo "trying to save the trajectory"  
# this works only for ugv1 or ugv2 (do not use other robots)
rosservice call /robot_trajectory_saver_node/save_robot_trajectories_only "file_path: '$DEST_FOLDER/trajectory.dot'"
check_status

echo DONE


