#!/usr/bin/env bash
# Author: Luigi Freda 

# N.B.: 
# 1) this script is designed just for testing the path planning nodes; no SLAM nodes are called; SLAM is assumed to be faked by a proper V-REP environment
# 2) you can kill all the spawned terminals together by right clicking on the X icon on the left bar and selecting "Quit"


LAUNCH_VREP=1 # 1 automatic launch of VREP, 0 no automatic launch
LAUNCH_VREP_MODE=2 # 0 launch VREP in normal mode (you have to press the button play to start)
	               # 1 launch VREP in headless mode (hidden) and automatically start it
	               # 2 launch VREP in normal mode and automatically start it (you will not be able to pause!)

# the following worlds are available in the folder "patrolling_ws/src/vrep/vrep_ugv_simulation/data"
#WORLD_NAME=ugv1_rescue_grousers 
WORLD_NAME=ugv1n2_rescue_grousers
#WORLD_NAME=3Dring1
#WORLD_NAME=3Dcrossroad_rooms3

NUM_ROBOTS=2

export XTERM_OPTIONS="-hold -iconic" # the "iconic" option allows to automatically minimize all the launched xterms

########################################################################################################

if [[ -z "${MR3D_HOME}" ]]; then
    echo "ERROR: missing env var MR3D_HOME"
    echo "please, source source_all.bash in the main 3DMR folder"
    exit 
else
    source $MR3D_HOME/source_all.bash
fi

########################################################################################################

if [[ -z "${LAUNCH_VREP_MODE_ENV}" ]]; then
  #using default value
  true
else
  LAUNCH_VREP_MODE="${LAUNCH_VREP_MODE_ENV}"
  echo "set from env var - LAUNCH_VREP_MODE: $LAUNCH_VREP_MODE"  
fi

if [[ -z "${ENABLE_MULTI_ROBOT_COORDINATION}" ]]; then
    ENABLE_MULTI_ROBOT_COORDINATION="true"
fi

if [[ -z "${ENABLE_TEB_LOCAL_PLANNER}" ]]; then
    ENABLE_TEB_LOCAL_PLANNER=0
fi

if [[ -z "${ENABLE_VOXBLOX}" ]]; then
    ENABLE_VOXBLOX=0
fi

########################################################################################################
#- VREP

if [ $LAUNCH_VREP -eq 1 ]; then
    echo "launching vrep"
    open_term VREP "echo vrep; roslaunch vrep_ugv_simulation vrep_ugv_simulation.launch map:=$WORLD_NAME headless:=$LAUNCH_VREP_MODE; bash" &
    sleep 8
fi

########################################################################################################
#- PATH PLANNERS

for i in `seq 1 $NUM_ROBOTS`; do
  echo launching robot ugv$i 
	rosrun path_planner sim_launcher_ugv $i $ENABLE_MULTI_ROBOT_COORDINATION $ENABLE_TEB_LOCAL_PLANNER $ENABLE_VOXBLOX  
  sleep 1
done  

########################################################################################################
#- RVIZ

open_term RVIZ "echo rviz; roslaunch path_planner rviz_sim_path_planning.launch; bash" &


########################################################################################################

echo DONE 

# NOTE: you can use the following command to get the xterm window live if the app terminates or crashes
# xterm $XTERM_OPTIONS -e "<you_command>; bash" &

                                                   



