#!/usr/bin/env bash

rosnode kill -a
sleep 1

killall -9 screen; screen -wipe 

killall -9 xterm
killall -9 vrep
killall -9 python

killall -9 roslaunch
killall -9 rosmaster
killall -9 rosout
killall -9 joynode
killall -9 rviz 
killall -9 rostopic

kill $(ps aux | grep ros | grep -v grep | awk '{print $2}')
