#!/usr/bin/env python3

# /**
# * This file is part of the ROS package trajectory_control which belongs to the framework 3DMR. 
# *
# * Copyright (C) 2016-present Luigi Freda <luigifreda at gmail dot com> and Alcor Lab (La Sapienza University)
# * For more information see <https://github.com/luigifreda/3dmr>
# *
# * 3DMR is free software: you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation, either version 3 of the License, or
# * (at your option) any later version.
# *
# * 3DMR is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with 3DMR. If not, see <http://www.gnu.org/licenses/>.
# */

import sys

from PyQt5 import QtCore, QtWidgets, QtGui

import rospy
import std_msgs.msg
import geometry_msgs.msg
import subprocess

keys = {
    QtCore.Qt.Key_Insert: 0,
    QtCore.Qt.Key_Delete: 0,
    QtCore.Qt.Key_PageUp: 0,
    QtCore.Qt.Key_PageDown: 0,
    QtCore.Qt.Key_Home: 0,
    QtCore.Qt.Key_End: 0,
    QtCore.Qt.Key_Left: 0,
    QtCore.Qt.Key_Right: 0,
    QtCore.Qt.Key_Up: 0,
    QtCore.Qt.Key_Down: 0,
    QtCore.Qt.Key_0: 0,
    QtCore.Qt.Key_S: 0,
    QtCore.Qt.Key_W: 0,
    QtCore.Qt.Key_D: 0,
    QtCore.Qt.Key_A: 0,
    QtCore.Qt.Key_Plus: 0,
    QtCore.Qt.Key_Minus: 0
}

control_movement = True
control_flippers = True
use_twist = True

robot_name='ugv1'
wheel_radius = 0.09
wheel_distance = 0.397

travel_speed = 4
steering_speed = travel_speed #0.66 * travel_speed
travel_speed_increment = 0.05

tlv = 0
trv = 0

'''
NOTE: this implementation has a limitation in Qt5. When a key is released the autorepeat is stopped and you need to repress the key in 
order to get the corresponding command!
'''
class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__(None, QtCore.Qt.WindowStaysOnTopHint)
        self.initUI()
        
        
    def getScreenResolution(self):
        output = subprocess.Popen('xrandr | grep "\*" | cut -d" " -f4',shell=True, stdout=subprocess.PIPE).communicate()[0]
        resolution = output.split()[0].split(b'x')
        print('resolution: '+str(resolution))
        return resolution
    
        
    def initUI(self):
        robot_id = 0
        try: 
            digit = [int(s) for s in list(robot_name) if s.isdigit()] # we expect only one digit
            robot_id = digit[0]
        except:
            robot_id = 0 
        resolution = self.getScreenResolution()
        self.setGeometry(int(resolution[0])-200, int(resolution[1])-350+ robot_id*100, 500, 1)
        self.setWindowTitle('TeleOp '+robot_name)
        self.show()
    
    def keyPressEvent(self, e):
        if e.key() in keys.keys():
            keys[e.key()] = 1
            print(f'{e.key()} -> 1')
            self.update()

    def keyReleaseEvent(self, e):
        if e.key() in keys.keys():
            if not e.isAutoRepeat(): # e.isAutoRepeat() returns true when the event is automatically generated 
                keys[e.key()] = 0
                print(f'{e.key()} -> 0')
                self.update()            

    def update(self):
        global travel_speed
        global tw, tl, tr, tlv, trv, travel_speed, steering_speed
        trv = 0
        tlv = 0   
        if keys[QtCore.Qt.Key_Left]: trv += steering_speed; tlv += -steering_speed
        if keys[QtCore.Qt.Key_Right]: trv += -steering_speed; tlv += steering_speed
        if keys[QtCore.Qt.Key_Up]: trv += travel_speed; tlv += travel_speed
        if keys[QtCore.Qt.Key_Down]: trv += -travel_speed; tlv += -travel_speed
        if keys[QtCore.Qt.Key_Plus]:
            travel_speed += travel_speed_increment; steering_speed = travel_speed
            print('travel speed: %f' % travel_speed)
        if keys[QtCore.Qt.Key_Minus]:
            travel_speed = max(travel_speed-travel_speed_increment,0); steering_speed = travel_speed
            print('travel speed: %f' % travel_speed)
        if control_movement:
            if use_twist:
                twm = geometry_msgs.msg.Twist()
                twm.linear.x = 0.5*(tlv+trv)*wheel_radius 
                twm.angular.z = (trv-tlv)*wheel_radius/wheel_distance 
                tw.publish(twm)
            else:
                tl.publish(std_msgs.msg.Float32(tlv))
                tr.publish(std_msgs.msg.Float32(trv))
        
def main():

    global robot_name, tw, tl, tr, travel_speed, steering_speed, wheel_radius, wheel_distance

    rospy.init_node('gazebo_jackal_teleop_key')
    robot_name = rospy.get_param('~robot_name', [])
    robot_prefix = rospy.get_param('~robot_prefix', [])        
    wheel_radius = rospy.get_param('~wheel_radius', 0.09)
    wheel_distance = rospy.get_param('~wheel_distance', 0.397)    
    print(f'using robot name: {robot_name}')
    print(f'using wheel radius: {wheel_radius}')
    print(f'using wheel distance: {wheel_distance}')
               
    if use_twist:
        tw = rospy.Publisher(robot_prefix+'/cmd_vel', geometry_msgs.msg.Twist,queue_size=10)
        tl = None; tl = None
    else:
        tl = rospy.Publisher(robot_prefix+'/left_track/velocity', std_msgs.msg.Float32,queue_size=10)
        tr = rospy.Publisher(robot_prefix+'/right_track/velocity', std_msgs.msg.Float32,queue_size=10)
        tw = None
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    sys.exit(app.exec_())

'''
NOTE: this implementation has a limitation in Qt5. When a key is released the autorepeat is stopped and you need to repress the key in 
order to get the corresponding command!
'''
if __name__ == '__main__':
    main()

